INCLUDES = -ILPC17XX/Core
INCLUDES += -ILPC17XX/System
INCLUDES += -IDrivers/OLED_MONO
INCLUDES += -ILPC17XX/Peripherals/SysTick
INCLUDES += -ILPC17XX/Peripherals/SPI
INCLUDES += -ILPC17XX/Peripherals/PCLKPWR
